services:
  app:
    build: .
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - HOSTNAME=0.0.0.0
      - DEXAI_DB_URL=${DEXAI_DB_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    restart: always
